Customers = new Mongo.Collection('customers')
Batches = new Mongo.Collection('batches')
Items = new Mongo.Collection('items')
Ingredients = new Mongo.Collection('ingredients')
Labels = new Mongo.Collection('labels')
Scales = new Mongo.Collection('scales')
Printers = new Mongo.Collection('printers')
Company = new Mongo.Collection('company')