export var Customers = new Mongo.Collection('customers')
export var Batches = new Mongo.Collection('batches')
export var Items = new Mongo.Collection('items')
export var Ingredients = new Mongo.Collection('ingredients')
export var Labels = new Mongo.Collection('labels')
export var Scales = new Mongo.Collection('scales')
export var Printers = new Mongo.Collection('printers')
export var Company = new Mongo.Collection('company')