export const Customers = new Mongo.Collection('customers')
export const Batches = new Mongo.Collection('batches')
export const Items = new Mongo.Collection('items')
export const Ingredients = new Mongo.Collection('ingredients')
export const Labels = new Mongo.Collection('labels')
export const Scales = new Mongo.Collection('scales')
export const Printers = new Mongo.Collection('printers')
export const Company = new Mongo.Collection('company')